### ISSUE TITLE
Create new Organisation throws a 500 exception

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-deployment#3]
## Screenshots:

<img width="1261" alt="Screenshot 2023-12-27 at 21 12 09" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-deployment/assets/4491850/362f6e6d-cc8b-442b-9f19-85aecc1ce4b5">

<img width="1257" alt="Screenshot 2023-12-27 at 21 12 23" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-deployment/assets/4491850/c4a983d5-4141-4287-a3c0-d495b8d6057e">

## Logs:
```
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:11:46,577 INFO  [ckan.config.middleware.flask_app]  200 /api/i18n/en render time 0.010 seconds
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:12:11,074 ERROR [ckan.config.middleware.flask_app] [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads/group'
gdi-userportal-ckan-deployment-ckan-1  | Traceback (most recent call last):
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     rv = self.dispatch_request()
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/views.py", line 84, in view
gdi-userportal-ckan-deployment-ckan-1  |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/views.py", line 158, in dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     return current_app.ensure_sync(meth)(*args, **kwargs)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/group.py", line 862, in post
gdi-userportal-ckan-deployment-ckan-1  |     group = _action(u'group_create')(context, data_dict)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
gdi-userportal-ckan-deployment-ckan-1  |     result = _action(context, data_dict, **kw)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/action/create.py", line 946, in organization_create
gdi-userportal-ckan-deployment-ckan-1  |     return _group_or_org_create(context, data_dict, is_org=True)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/action/create.py", line 739, in _group_or_org_create
gdi-userportal-ckan-deployment-ckan-1  |     upload = uploader.get_uploader('group')
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 61, in get_uploader
gdi-userportal-ckan-deployment-ckan-1  |     upload = Upload(upload_to, old_filename)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 129, in __init__
gdi-userportal-ckan-deployment-ckan-1  |     os.makedirs(self.storage_path)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/os.py", line 225, in makedirs
gdi-userportal-ckan-deployment-ckan-1  |     mkdir(name, mode)
gdi-userportal-ckan-deployment-ckan-1  | PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads/group'
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:12:11,111 INFO  [ckan.config.middleware.flask_app]  500 /organization/new render time 0.061 seconds
```

**Comment by zalborzi** [comment]
you may manually give access to /var/lib/ckan/storage/uploads/ and it will be resolved for group/organization.

**Comment by brunopacheco1** [comment]
I tried and it works, but this does not seem to be an ideal solution. For me it looks like a side-effect of a misconfiguration in the Dockerfile, perhaps a different users are creating files in the same folder? And the one used by CKAN does not have the right permissions.
